apiVersion: v1
kind: Secret
metadata:
  name: account-secret
type: Opaque
data:
  datasource-password: cGFzc3dvcmQ= # "password" Ğ² base64

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
